### ISSUE TITLE
remove clear-timeouts ?

### ISSUE THREAD

**Issue by yields** [segmentio/clear-env#2]
i can't upgrade our repos to the latest duo-test because mocha uses it to emit events, timeout of tests etc..

**Comment by ndhoule** [comment]
Actual problem here is `clear-scripts`, which is removing the jsonp scripts duo-test is adding to the page after `clear-scripts` has recorded a snapshot of the current scripts on the page. For some reason this problem only affects pre-ES5 browsers; tested IE8, PhantomJS (which is mostly only ES3-compliant).

Hacky fix here for the curious: https://github.com/segmentio/clear-scripts/commit/99094b1b437608cec2323ffbfe7b063bbd5d3d5a
